### ISSUE TITLE
BSXPCMessage received error for message: Connection interrupted

### ISSUE THREAD

**Issue by Sun3** [dataxpress/UICountingLabel#27]
I have run into an issue with using UICountingLabel. It is causing an BSXPCMessage error. Any ideas?

```
BSXPCMessage received error for message: Connection interrupted
```

**Comment by dataxpress** [comment]
Looks like this is a bug in iOS 8 unrelated to UICountingLabel: http://stackoverflow.com/questions/26065808/bsxpcmessage-received-error-for-message-connection-interrupted
