### ISSUE TITLE
Has anyone been able to get this to work with the @"%d" format, or showing a float with no decimal values?

### ISSUE THREAD

**Issue by mitchellporter** [dataxpress/UICountingLabel#31]
All I want to do is count from a value like 0 to 38. I don't want to display any decimal points or numbers after a decimal point. Just want a simple number like "38" or "500".

Is anyone successfully doing this? If I set my format to `@"%d"`, the label counts up weird and stops at the wrong value. I have tried hacking around in the repo and using formatted strings but nothing seems to work.

Is anyone successfully doing this, or does anyone know how it can be done?

Thanks for the help!

**Comment by dataxpress** [comment]
Can you post the code you're using?

**Comment by mitchellporter** [comment]
@dataxpress Unfortunately i was trying to move very quickly and never saved or committed any of the code. However, I followed all of the basic instructions and was trying to use the `%d` format. I'm on Xcode 6.1.1 as well.
