### ISSUE TITLE
provide method to initialize counter

### ISSUE THREAD

**Issue by cranmer** [dataxpress/UICountingLabel#32]
Hi

This is a very useful pod. I wasn't able to figure out how to initialize the counter to something other than 0. Right now my viewDidLoad has
```    [self.myLabel countFrom:123 to:123 withDuration:0.0f ];```
as an example to initialize to 123.

The currentValue property doesn't have associated get/set options.
(I could also be making a silly mistake, I'm somewhat new to iOS and objective C)

**Comment by dataxpress** [comment]
as it is a subclass of UILabel you can just access the `self.myLabel.text` property. 

    self.myLabel.text = @"123";

note that writing to this property while the counter is running will cause it to be quickly overwritten, so setting this way is only recommended before or after counting.
