### ISSUE TITLE
add animation effect

### ISSUE THREAD

**Issue by cranmer** [dataxpress/UICountingLabel#33]
I was hoping for an odometer effect like this
http://github.hubspot.com/odometer/api/themes/

it seems like using `kCATransitionFromBottom` this should be possible.

```
  // Add transition (must be called after myLabel has been displayed)
    CATransition *animation = [CATransition animation];
    animation.duration = .3;
    animation.type = kCATransitionFromBottom;
    animation.timingFunction = [CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionEaseInEaseOut];
    [_instructions.layer addAnimation:animation forKey:@"changeTextTransition"];

    // Change the text
    _instructions.text = @"127";
```

**Comment by dataxpress** [comment]
it should work with this - just replace `_instructions` with your instance of the UICountingLabel. Might have to play with the `duration` setting to get it to look how you want it.
