### ISSUE TITLE
Use comma instead of period? 

### ISSUE THREAD

**Issue by npersson** [dataxpress/UICountingLabel#34]
Great extension! 
Is it possible to get UICountingLabel to work with a comma instead of a period as a decimal point? Eg 1,3 instead of 1.3. 
Have tried format = @"%,1f";

**Comment by dataxpress** [comment]
might need to use something like 

    NSNumberFormatter *numberFormatter = [[NSNumberFormatter alloc] init];
    numberFormatter.locale = [NSLocale currentLocale];
    numberFormatter.numberStyle = NSNumberFormatterDecimalStyle;
    numberFormatter.usesGroupingSeparator = YES;
    return [numberFormatter stringFromNumber:@(floatValue)];

of course, i would initialize the number formatter once and then just use the `stringFromNumber:` call within the block
