### ISSUE TITLE
Leading zeros

### ISSUE THREAD

**Issue by JamaicanRumCream** [dataxpress/UICountingLabel#53]
Would be nice to be able to specify a fixed number of characters so it would automatically pad with leading zeros.

**Comment by dataxpress** [comment]
You can do this with the `format` property, for example `%02d` will be an integer that is always 2 or more digits long.

**Comment by dataxpress** [comment]
[here is a decent reference](http://www.ios-developer.net/iphone-ipad-programmer/development/strings/displaying-values-in-strings)

**Comment by JamaicanRumCream** [comment]
Oh just figured that out! Thanks!
